CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username TEXT UNIQUE NOT NULL,
    pw_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    order_num TEXT UNIQUE NOT NULL,
    user_id INT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS point_accounts (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    balance NUMERIC(12,2),
    user_id INT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS withdrawal_history (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    amount NUMERIC(12,2),
    point_account_id INT REFERENCES point_accounts(id)
);
